name: publish

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  create-docker-image:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build production image
        run: |
          IMAGE=ghcr.io/luirrodev/simco-stats-api:latest
          echo "Building production image using --target production..."
          docker build --target production . --tag $IMAGE
          echo "Pushing $IMAGE to registry..."
          docker push $IMAGE

      - name: Deploy to Render
        if: success() && github.ref == 'refs/heads/main'
        run: |
          echo "Triggering deployment to Render..."
          response=$(curl -s -o /dev/null -w "%{http_code}" -X GET "${{ secrets.RENDER_DEPLOY_HOOK }}")
          if [ "$response" -eq 200 ]; then
            echo "✅ Deployment triggered successfully!"
          else
            echo "❌ Failed to trigger deployment. HTTP status: $response"
            exit 1
          fi
